OUT_DIR := ../../dist/program

# BPF target
#
#SOLANA_TOOLS = $(shell dirname $(shell which cargo-build-bpf))
#include $(SOLANA_TOOLS)/sdk/bpf/c/bpf.mk

# SBF target
#
SOLANA_TOOLS = $(ADALABS_ROOT_PATH)/GitHub/solana
include $(SOLANA_TOOLS)/sdk/sbf/c/sbf.mk
